[workspace]
resolver = "2"
members = [
    "crates/concurrent-exclusive-lock",
    "crates/test-and-benchmark",
]
default-members = [
    "crates/concurrent-exclusive-lock",
    "crates/test-and-benchmark",
]
exclude = [
    "vendor/parking_lot",
]

[workspace.package]
version = "1.0.0"
edition = "2021"
rust-version = "1.75"
authors = ["YiBoWang <wyb_passport@hotmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/WangHHB/ConcurrentExclusiveLock"
homepage = "https://github.com/WangHHB/ConcurrentExclusiveLock"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "unwind"
strip = false

[patch.crates-io]
cfg-if = { path = "vendor/cfg-if" }
libc = { path = "vendor/libc" }
smallvec = { path = "vendor/smallvec" }
scopeguard = { path = "vendor/scopeguard" }
windows-link = { path = "vendor/windows-link" }
